const STORE = {
    questions: [{question: 'Sookie\'s last name is ___.',
        options: ['Compton', 'Merlotte', 'Stackhouse', 'Thornton'],
        answer: 'Stackhouse'},
        {question: 'Who was NOT one of Sookie\'s love interests?',
        options: ['Sam Merlotte', 'Eric Northman', 'Alcide Herveaux', 'Steve Newlin'],
        answer: 'Steve Newlin'},
        {question: 'Arlene was a ___.',
        options: ['chef', 'waitress', 'bartender', 'host'],
        answer: 'waitress'},
        {question: 'The show takes place in ___.',
        options: ['New Orleans', 'Hawkins', 'Mystic Falls', 'Bon Temps'],
        answer: 'Bon Temps'},
        {question: 'Which supernatural creatures do NOT appear on the show?',
        options: ['Jinns', 'Shapeshifters', 'Witches', 'Faeries'],
        answer: 'Jinns'},
        {question: 'Sookie\'s best friend was ___.',
        options: ['Sarah', 'Ginger', 'Marnie', 'Tara'],
        answer: 'Tara'},
        {question: 'Jessica was made a vampire by ___.',
        options: ['Lafayette', 'Bill', 'Eric', 'Roman'],
        answer: 'Bill'},
        {question: 'Jason was addicted to ___.',
        options: ['sex', 'gambling', 'cocaine', 'alcohol'],
        answer: 'sex'},
        {question: 'The show name "True Blood" refers to a ___.',
        options: ['restaurant name', 'drink name', 'blood type', 'drug name'],
        answer: 'drink name'},
        {question: 'By the final season, we know Sookie to be part ___.',
        options: ['werewolf', 'witch', 'vampire', 'faerie'],
        answer: 'faerie'}],
    currentQuestion: 0,
    correctAnswerCount: 0
};